title: Sakhi Khanchandani # your name (or website title) here
logo: "/images/e4537446-1c0b-44b2-98b6-217f3f0b4776.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a master's student at Carnegie Mellon University, specializing in Business Intelligence and Data Analytics (BIDA). With a strong foundation in data science and product management, I thrive at turning complex data into actionable insights that drive strategic decisions. My experience spans high-growth startups, where I’ve navigated fast-paced environments, optimized processes, and contributed to impactful projects. What sets me apart is my ability to balance analytical depth with a user-centric mindset—ensuring data not only informs but also enhances real-world experiences. I am passionate about leveraging technology and analytics to solve meaningful problems and create measurable value.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
